/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoa3.footcup2022;

import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import projetoa3.footcup2022.Lib.Usuario;

/**
 *
 * @author digog
 */
public class frmCadUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDeUsuarios
     */
    public frmCadUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jlblUser7 = new javax.swing.JLabel();
        jbtnSimJogos7 = new javax.swing.JButton();
        jbtnVisualizarTimes7 = new javax.swing.JButton();
        jbtnVisualizarGrp7 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jlblUserIcon7 = new javax.swing.JLabel();
        jbtnCadTimes14 = new javax.swing.JButton();
        jbtnCadGrp7 = new javax.swing.JButton();
        jbtnVisualizarJogos7 = new javax.swing.JButton();
        jbtnCadTimes15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtSenha1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jtxtSenha2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(42, 170, 56));

        jlblUser7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlblUser7.setForeground(new java.awt.Color(255, 255, 255));
        jlblUser7.setText("Bem vindo, $usr$!");

        jbtnSimJogos7.setText("Simulador de Jogos");

        jbtnVisualizarTimes7.setText("Visualizar Times");

        jbtnVisualizarGrp7.setText("Visualizar Grupos");

        jButton13.setText("Sair");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jlblUserIcon7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlblUserIcon7.setForeground(new java.awt.Color(255, 255, 255));
        jlblUserIcon7.setText("  ");
        jlblUserIcon7.setToolTipText("<a href=\"https://www.flaticon.com/br/icones-gratis/admin\" title=\"admin ícones\">Icone criado por Tanah Basah - Flaticon</a>");

        jbtnCadTimes14.setText("Cadastrar Times");

        jbtnCadGrp7.setText("Cadastrar Grupos");

        jbtnVisualizarJogos7.setText("Visualizar Jogos");

        jbtnCadTimes15.setText("Cadastrar Usuario");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlblUserIcon7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jlblUser7))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnCadTimes15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnCadTimes14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnVisualizarJogos7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnCadGrp7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnVisualizarGrp7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnSimJogos7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnVisualizarTimes7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jlblUserIcon7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblUser7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnVisualizarJogos7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnVisualizarTimes7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnVisualizarGrp7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jbtnCadTimes15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCadTimes14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCadGrp7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSimJogos7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Usuario");

        jtxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Senha");

        jtxtSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSenha1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Confirmar Senha");

        jtxtSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSenha2ActionPerformed(evt);
            }
        });

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtxtSenha1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                        .addComponent(jtxtUsuario))
                                    .addComponent(jLabel2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jtxtSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(85, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButton1)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        frmLogin frm = new frmLogin();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jtxtSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSenha1ActionPerformed

    private void jtxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String novoUsuario = jtxtUsuario.getText();
        String novoSenha1 = jtxtSenha1.getText();
        String novoSenha2 = jtxtSenha2.getText();
        
        if (novoSenha1.equals(novoSenha2)){
            Usuario objUsuario = new Usuario(novoUsuario,novoSenha1);
            
            try {
                if(objUsuario.CadastrarUsuario(novoUsuario, novoSenha1))
                {
                    JOptionPane.showMessageDialog(null, "Usuario cadastrado com sucesso!");
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Erro no cadastro!");
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtSenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSenha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSenha2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton jbtnCadGrp;
    private javax.swing.JButton jbtnCadGrp1;
    private javax.swing.JButton jbtnCadGrp2;
    private javax.swing.JButton jbtnCadGrp3;
    private javax.swing.JButton jbtnCadGrp4;
    private javax.swing.JButton jbtnCadGrp5;
    private javax.swing.JButton jbtnCadGrp6;
    private javax.swing.JButton jbtnCadGrp7;
    private javax.swing.JButton jbtnCadTimes;
    private javax.swing.JButton jbtnCadTimes1;
    private javax.swing.JButton jbtnCadTimes10;
    private javax.swing.JButton jbtnCadTimes11;
    private javax.swing.JButton jbtnCadTimes12;
    private javax.swing.JButton jbtnCadTimes13;
    private javax.swing.JButton jbtnCadTimes14;
    private javax.swing.JButton jbtnCadTimes15;
    private javax.swing.JButton jbtnCadTimes2;
    private javax.swing.JButton jbtnCadTimes3;
    private javax.swing.JButton jbtnCadTimes4;
    private javax.swing.JButton jbtnCadTimes5;
    private javax.swing.JButton jbtnCadTimes6;
    private javax.swing.JButton jbtnCadTimes7;
    private javax.swing.JButton jbtnCadTimes8;
    private javax.swing.JButton jbtnCadTimes9;
    private javax.swing.JButton jbtnSimJogos;
    private javax.swing.JButton jbtnSimJogos1;
    private javax.swing.JButton jbtnSimJogos2;
    private javax.swing.JButton jbtnSimJogos3;
    private javax.swing.JButton jbtnSimJogos4;
    private javax.swing.JButton jbtnSimJogos5;
    private javax.swing.JButton jbtnSimJogos6;
    private javax.swing.JButton jbtnSimJogos7;
    private javax.swing.JButton jbtnVisualizarGrp;
    private javax.swing.JButton jbtnVisualizarGrp1;
    private javax.swing.JButton jbtnVisualizarGrp2;
    private javax.swing.JButton jbtnVisualizarGrp3;
    private javax.swing.JButton jbtnVisualizarGrp4;
    private javax.swing.JButton jbtnVisualizarGrp5;
    private javax.swing.JButton jbtnVisualizarGrp6;
    private javax.swing.JButton jbtnVisualizarGrp7;
    private javax.swing.JButton jbtnVisualizarJogos;
    private javax.swing.JButton jbtnVisualizarJogos1;
    private javax.swing.JButton jbtnVisualizarJogos2;
    private javax.swing.JButton jbtnVisualizarJogos3;
    private javax.swing.JButton jbtnVisualizarJogos4;
    private javax.swing.JButton jbtnVisualizarJogos5;
    private javax.swing.JButton jbtnVisualizarJogos6;
    private javax.swing.JButton jbtnVisualizarJogos7;
    private javax.swing.JButton jbtnVisualizarTimes;
    private javax.swing.JButton jbtnVisualizarTimes1;
    private javax.swing.JButton jbtnVisualizarTimes2;
    private javax.swing.JButton jbtnVisualizarTimes3;
    private javax.swing.JButton jbtnVisualizarTimes4;
    private javax.swing.JButton jbtnVisualizarTimes5;
    private javax.swing.JButton jbtnVisualizarTimes6;
    private javax.swing.JButton jbtnVisualizarTimes7;
    private javax.swing.JLabel jlblUser;
    private javax.swing.JLabel jlblUser1;
    private javax.swing.JLabel jlblUser2;
    private javax.swing.JLabel jlblUser3;
    private javax.swing.JLabel jlblUser4;
    private javax.swing.JLabel jlblUser5;
    private javax.swing.JLabel jlblUser6;
    private javax.swing.JLabel jlblUser7;
    private javax.swing.JLabel jlblUserIcon;
    private javax.swing.JLabel jlblUserIcon1;
    private javax.swing.JLabel jlblUserIcon2;
    private javax.swing.JLabel jlblUserIcon3;
    private javax.swing.JLabel jlblUserIcon4;
    private javax.swing.JLabel jlblUserIcon5;
    private javax.swing.JLabel jlblUserIcon6;
    private javax.swing.JLabel jlblUserIcon7;
    private javax.swing.JPasswordField jtxtSenha1;
    private javax.swing.JPasswordField jtxtSenha2;
    private javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
